name: Node CI

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 21.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm ci
        npm test
      env:
        CI: true
  
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4      
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        registry-url: 'https://registry.npmjs.org'
    - name: release
      run: |
        npm run release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
